name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version (adjust based on your app)

    - name: Install dependencies
      run: npm install  # Install project dependencies

    - name: Run tests
      run: npm test  # Run tests (make sure you have a test script in package.json)

    - name: Build project
      run: npm run build  # Optionally, run a build script if you have one

    - name: Deploy to Staging
      run: npm run deploy  # Run a deployment script (make sure it's defined in package.json)
